export const plans = [
  {
    id: 1,
    planKey: "starter",
    name: "starter",
    price: "$29",
    description: "Perfect for small teams and startups.",
    features: [
      "Up to 5 team members",
      "Basic analytics",
      "5GB storage",
      "Email support",
    ],
    buttonText: "Start Free Trial",
    priceId: "price_1RL7bbC5mDXBy5X6BXYOfDtT",
  },
  {
    id: 2,
    name: "Professional",
    planKey: "professional",
    price: "$79",
    description: "Ideal for growing businesses.",
    features: [
      "Up to 20 team members",
      "Advanced analytics",
      "25GB storage",
      "Priority email support",
      "API access",
    ],
    buttonText: "Start Free Trial",
    popular: true,
    priceId: "price_1RL7cFC5mDXBy5X66QT8GGUR",
  },
  {
    id: 3,
    name: "Enterprise",
    description: "For large organizations with complex needs.",
    price: "$199",
    features: [
      "Up to 20 team members",
      "Advanced analytics",
      "25GB storage",
      "Priority email support",
      "API access",
    ],
    buttonText: "Start Free Trial",
    priceId: "price_1RL7cnC5mDXBy5X6zYBcjcBK",
  },
];
